FROM node:22-alpine

WORKDIR /app/client

ENV NODE_ENV=development

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

EXPOSE 5174

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5174"]
